# Generated by Django 5.2.5 on 2025-09-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_zodiac_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zodiac_sign',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
