# Generated by Django 5.2.5 on 2025-09-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_zodiac_sign'),
    ]

    operations = [
    ]
