# Generated by Django 5.2.4 on 2025-09-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_convert_zodiac_to_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zodiac_sign',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
