# Generated by Django 4.2.23 on 2025-06-25 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.TextField(verbose_name='transcription du rêve')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date du rêve')),
                ('image64', models.TextField(blank=True, null=True, verbose_name='image encodée en base64')),
            ],
        ),
    ]
