# Generated by Django 5.2.3 on 2025-06-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_bridge_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='emotion',
            field=models.CharField(choices=[('joie', 'Joie'), ('tristesse', 'Tristesse'), ('colère', 'Colère'), ('peur', 'Peur'), ('surprise', 'Surprise'), ('dégoût', 'Dégoût')], default='joie', max_length=20),
            preserve_default=False,
        ),
    ]
