# Generated by Django 5.2.3 on 2025-06-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_bridge_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='prompt',
            field=models.TextField(default='prompt non saisie', verbose_name='used prompt for image generation'),
            preserve_default=False,
        ),
    ]
