# Generated by Django 5.2.3 on 2025-06-26 15:36

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_bridge_app', '0002_dream_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dream',
            name='image64',
        ),
        migrations.RemoveField(
            model_name='dream',
            name='prompt',
        ),
        migrations.AddField(
            model_name='dream',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 26, 15, 36, 51, 546253, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dream',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dream',
            name='generated_image',
            field=models.ImageField(blank=True, help_text='The final image generated from the dream.', null=True, upload_to='dreams/images/'),
        ),
        migrations.AddField(
            model_name='dream',
            name='image_prompt',
            field=models.TextField(blank=True, help_text='The prompt generated for the text-to-image model.'),
        ),
        migrations.AddField(
            model_name='dream',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='dream',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dream',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dream',
            name='transcription',
            field=models.TextField(blank=True, help_text='The text transcribed from the audio file.'),
        ),
    ]
