# Generated by Django 5.2.3 on 2025-06-26 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_bridge_app', '0003_remove_dream_date_remove_dream_image64_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='dreams', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
