# Generated by Django 5.2.4 on 2025-07-22 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream_bridge_app', '0002_dream_emotion'),
        ('dream_bridge_app', '0004_dream_user'),
    ]

    operations = [
    ]
