# Generated by Django 5.2.5 on 2025-09-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_bridge_app', '0005_merge_0002_dream_emotion_0004_dream_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='phrase',
            field=models.TextField(blank=True, default='', help_text='Daily quote / astro message'),
        ),
        migrations.AddField(
            model_name='dream',
            name='phrase_date',
            field=models.DateField(blank=True, help_text="Date when 'phrase' was last updated", null=True),
        ),
    ]
