# Generated by Django 5.2.6 on 2025-09-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_bridge_app', '0005_merge_0002_dream_emotion_0004_dream_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='emotion',
            field=models.CharField(blank=True, choices=[('joie', 'Joie'), ('tristesse', 'Tristesse'), ('colère', 'Colère'), ('peur', 'Peur'), ('surprise', 'Surprise'), ('dégoût', 'Dégoût')], default='neutre', max_length=20),
        ),
    ]
