# Generated by Django 5.2.4 on 2025-09-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream_bridge_app', '0006_alter_dream_emotion'),
        ('dream_bridge_app', '0006_dream_phrase_dream_phrase_date'),
    ]

    operations = [
    ]
