# Generated by Django 5.2.5 on 2025-09-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_bridge_app', '0007_merge_20250915_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='personal_phrase',
            field=models.TextField(blank=True, default='', help_text='Personalized message based on the dream.'),
        ),
        migrations.AddField(
            model_name='dream',
            name='personal_phrase_date',
            field=models.DateField(blank=True, help_text="Date when 'personal_phrase' was last updated", null=True),
        ),
        migrations.AlterField(
            model_name='dream',
            name='emotion',
            field=models.CharField(blank=True, choices=[('neutre', 'Neutre'), ('joie', 'Joie'), ('tristesse', 'Tristesse'), ('colère', 'Colère'), ('peur', 'Peur'), ('surprise', 'Surprise'), ('dégoût', 'Dégoût')], default='neutre', max_length=20),
        ),
    ]
