on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Create and activate virtual environment + install dependencies + lint + migrate + collectstatic
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r dream_bridge/requirements.txt
        python dream_bridge/manage.py migrate
        python dream_bridge/manage.py collectstatic --noinput

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd /home/ubuntu/CICD_TEST/dream_bridge
          git pull origin main
          source venv/bin/activate
          pip install -r dream_bridge/requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart django
          sudo systemctl restart celery
